'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Download,Inbox,RefreshCw} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
type Order={id:string;reference:string;name:string;email:string;phone:string;details:string;status:string;artwork_name:string|null;created_at:number};
export default function RequestInbox(){
 const[orders,setOrders]=useState<Order[]>([]),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('all'),[pending,setPending]=useState(false),[signedOut,setSignedOut]=useState(false);
 async function load(){setLoading(true);setError('');try{const res=await fetch('/api/requests');const data=await res.json() as {error?:string;requests:Order[];admin:boolean};if(res.status===401)setSignedOut(true);if(!res.ok)throw new Error(data.error||'Unable to load requests.');setOrders(data.requests);setAdmin(data.admin)}catch(e){setError(e instanceof Error?e.message:'Unable to load requests.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const current=orders.find(o=>o.id===selected);const detail=current?JSON.parse(current.details):null;const visible=orders.filter(o=>filter==='all'||o.status===filter);
 async function status(value:string){if(!current)return;setPending(true);setError('');try{const res=await fetch('/api/requests/'+current.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:value})});const data=await res.json() as {error?:string;requests:Order[];admin:boolean};if(!res.ok)throw new Error(data.error||'Unable to update request.');setOrders(v=>v.map(o=>o.id===current.id?{...o,status:value}:o))}catch(e){setError(e instanceof Error?e.message:'Unable to update request.')}finally{setPending(false)}}
 return <><header className="site-header wrap"><a className="wordmark" href="/">make it<span>personalized.</span></a><a href="/" className="text-link"><ArrowLeft size={16}/> Back to the studio</a></header><main className="wrap inbox-page"><div className="inbox-heading"><div><p className="eyebrow">{admin?'STUDIO WORKSPACE':'YOUR PERSONAL PROJECTS'}</p><h1>{admin?'Request inbox.':'My requests.'}</h1><p className="muted">{admin?'Review the details. Make something great.':'Your saved ideas and their latest progress.'}</p></div><button className="button secondary small" onClick={load} disabled={loading}><RefreshCw size={16}/> Refresh</button></div>
 {error&&<p role="alert" className="form-error">{error}</p>}{signedOut&&<a className="button" href="/signin-with-chatgpt?return_to=%2Frequests" target="_top">Sign in to view requests <ArrowRight size={16}/></a>}
 {!signedOut&&<><div className="inbox-toolbar"><span>{orders.length} {orders.length===1?'request':'requests'}</span><Select value={filter} onValueChange={v=>v&&setFilter(v)}><SelectTrigger aria-label="Filter by status" className="form-select"><SelectValue/></SelectTrigger><SelectContent>{['all','new','reviewing','awaiting approval','in production','ready','closed'].map(v=><SelectItem key={v} value={v}>{v==='all'?'All statuses':v}</SelectItem>)}</SelectContent></Select></div>
 {loading?<p role="status" className="empty-state">Loading your requests…</p>:orders.length===0?<div className="empty-state"><Inbox size={36}/><h2>Every project starts with an idea.</h2><p>Your requests will appear here once you send them.</p><a className="button" href="/customize">Start a project <ArrowRight size={17}/></a></div>:<div className="inbox-layout"><div className="request-list">{visible.length===0?<p className="empty-state">No requests with this status.</p>:visible.map(o=><button className={'request-card '+(selected===o.id?'selected':'')} onClick={()=>setSelected(o.id)} key={o.id}><span className="request-card-top"><strong>{o.reference}</strong><span className="status-pill">{o.status}</span></span><h3>{JSON.parse(o.details).quantity} × {JSON.parse(o.details).product}</h3><p>{o.name} · {new Date(o.created_at).toLocaleDateString()}</p><span>View request <ArrowRight size={15}/></span></button>)}</div><section className="request-detail" aria-label="Request details">{current?<><p className="eyebrow">{current.reference}</p><h2>{detail.product}</h2><p className="muted">Received {new Date(current.created_at).toLocaleString()}</p>{admin?<div className="field"><label>Status</label><Select disabled={pending} value={current.status} onValueChange={v=>v&&void status(v)}><SelectTrigger className="form-select" aria-label="Request status"><SelectValue/></SelectTrigger><SelectContent>{['new','reviewing','awaiting approval','in production','ready','closed'].map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></div>:<p className="status-pill">{current.status}</p>}<dl className="detail-grid">{[['Quantity',detail.quantity],['Color',detail.color],['Size',detail.size],['Placement',detail.placement],['For',detail.purpose],['Requested date',detail.neededBy||'Flexible'],['Fulfillment','Local pickup']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>Personalization</h3><p className="preserve">{detail.text||'No text requested.'}</p><h3>Notes</h3><p className="preserve">{detail.notes||'No additional notes.'}</p>{current.artwork_name&&<a className="button secondary small" href={'/api/requests/'+current.id}><Download size={16}/> {current.artwork_name}</a>}<h3>Contact</h3><p>{current.name}<br/><a href={'mailto:'+current.email}>{current.email}</a><br/>{current.phone&&<a href={'tel:'+current.phone}>{current.phone}</a>}</p><p className="field-hint">This is an order request. Confirm the artwork, price and timing directly with the customer before production.</p></>:<div className="empty-state"><Inbox size={30}/><p>Select a request to view its details.</p></div>}</section></div>}</>}
 </main><footer className="wrap footer"><a href="/privacy">Privacy</a><a href="/customize">Start another project</a></footer></>;
}
