import {database,files,identity,sameOrigin,json} from '@/lib/server';
import {validateOrder,validateContact} from '@/lib/order-validation';
export async function POST(request:Request){
 if(!sameOrigin(request))return json({error:'Please send your request from this website.'},403);
 const max=6*1024*1024;if(Number(request.headers.get('content-length'))>max)return json({error:'Your upload is too large. Maximum artwork size is 5 MB.'},413);
 let uploaded:string|null=null;let committed=false;
 try{
  const reader=request.body?.getReader();if(!reader)return json({error:'Missing request details.'},400);let bytes=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>max){await reader.cancel();return json({error:'Your upload is too large.'},413)}chunks.push(value)}
  const body=new Uint8Array(bytes);let offset=0;for(const chunk of chunks){body.set(chunk,offset);offset+=chunk.length}const form=await new Response(body,{headers:{'Content-Type':request.headers.get('content-type')||''}}).formData();
  if(form.get('website'))return json({error:'Unable to accept this request.'},400);
  if(form.get('consent')!=='yes')return json({error:'Please agree to be contacted about this request.'},400);
  const draft=validateOrder(JSON.parse(String(form.get('draft'))));const contact=validateContact(form.get('name'),form.get('email'),form.get('phone')||'');const key=String(form.get('idempotencyKey'));if(!/^[0-9a-f-]{36}$/i.test(key))return json({error:'Please reload the page and try again.'},400);
  const who=identity(request.headers);const db=database();const existing=await db.prepare('SELECT reference, owner_id, email FROM requests WHERE idempotency_key = ?').bind(key).first<{reference:string;owner_id:string|null;email:string}>();if(existing){if(existing.owner_id===who.id&&existing.email===contact.email)return json({reference:existing.reference});return json({error:'Please start a new request.'},409)}
  const ip=request.headers.get('cf-connecting-ip')||'local';const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip));const ipHash=Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');const recent=await db.prepare('SELECT COUNT(*) AS count FROM requests WHERE ip_hash = ? AND created_at > ?').bind(ipHash,Date.now()-600000).first<{count:number}>();if((recent?.count??0)>=10)return json({error:'Please wait a few minutes before submitting another request.'},429);
  const artwork=form.get('artwork');let artworkName:string|null=null,artworkType:string|null=null;
  const id=crypto.randomUUID();const reference='MIP-'+id.slice(0,8).toUpperCase();
  if(artwork instanceof File&&artwork.size){if(artwork.size>5*1024*1024||!['image/png','image/jpeg','application/pdf'].includes(artwork.type))return json({error:'Choose a PNG, JPG or PDF up to 5 MB.'},400);const buf=await artwork.arrayBuffer();const a=new Uint8Array(buf);const valid=artwork.type==='image/png'?a[0]===137&&a[1]===80&&a[2]===78&&a[3]===71:artwork.type==='image/jpeg'?a[0]===255&&a[1]===216&&a[2]===255:new TextDecoder().decode(a.slice(0,5))==='%PDF-';if(!valid)return json({error:'The artwork file does not match its format.'},400);artworkName=artwork.name.replace(/[^\w.() -]/g,'_').slice(0,140)||'artwork';artworkType=artwork.type;uploaded='requests/'+id+'/artwork';await files().put(uploaded,buf,{httpMetadata:{contentType:artworkType}})}
  if(!draft.text&&!draft.notes&&!uploaded)return json({error:'Add text, artwork or a few notes about your idea.'},400);
  await db.prepare('INSERT INTO requests (id,reference,idempotency_key,owner_id,name,email,phone,details,status,artwork_key,artwork_name,artwork_type,ip_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,reference,key,who.id,contact.name,contact.email,contact.phone,JSON.stringify(draft),'new',uploaded,artworkName,artworkType,ipHash,Date.now()).run();committed=true;return json({reference},201);
 }catch(error){if(uploaded&&!committed)await files().delete(uploaded).catch(()=>{});const message=error instanceof Error?error.message:'';const validation=/^(Please|Choose|Quantity|Add |Your |Unable)/.test(message)||error instanceof SyntaxError;return json({error:validation?(error instanceof SyntaxError?'Please check your request details.':message):'We could not save your request. Please try again or call the studio.'},validation?400:500)}
}
export async function GET(request:Request){const who=identity(request.headers);if(!who.id)return json({error:'Sign in to view your requests.'},401);const stmt=who.admin?database().prepare('SELECT id,reference,name,email,phone,details,status,artwork_name,created_at FROM requests ORDER BY created_at DESC LIMIT 100'):database().prepare('SELECT id,reference,name,email,phone,details,status,artwork_name,created_at FROM requests WHERE owner_id = ? ORDER BY created_at DESC LIMIT 100').bind(who.id);const {results}=await stmt.all();return json({requests:results,admin:who.admin})}
