import HomeDetails from '@/components/home-details';
import { ArrowUpRight, ArrowRight, Sparkles, MapPin, Shirt, Scissors, PencilRuler, Coffee, Check } from 'lucide-react';
export default function Home() {
 return <>
 <header className="site-header wrap"><a href="/" className="wordmark">make it<span>personalized<span className="brand-dot">.</span></span></a><nav aria-label="Main navigation"><a href="#create">What we make</a><a href="#how">How it works</a><a href="#visit">Visit the studio</a></nav><a className="button small" href="/customize">Start your project <ArrowUpRight size={17}/></a></header>
 <main>
 <section className="hero wrap"><div className="hero-copy" data-reveal><p className="eyebrow"><Sparkles size={14}/> A little more you.</p><h1>Make it<br/><span>personal.</span></h1><p className="hero-description">Your ideas, on the things you love. Custom apparel, embroidery and engraved gifts, made just for you.</p><div className="hero-actions"><a className="button" href="/customize">Create something <ArrowRight size={18}/></a><a className="text-link" href="#create">Explore the possibilities <ArrowRight size={16}/></a></div><p className="hero-note"><Check size={15}/> One item or a whole team. You’re in the right place.</p></div><div className="hero-visual"><div className="hero-image"><img src="/products-hero.png" width="1536" height="1024" fetchPriority="high" alt="Personalization ideas: a printed shirt, embroidered cap, mug, tumbler and engraved tag"/></div><div className="hero-caption"><Sparkles size={20}/><div><strong>Your idea. Made real.</strong><span>A few possibilities to inspire you.</span></div></div></div></section>
 <div className="benefit-strip"><div className="wrap"><span>One item? Absolutely.</span><span>Family-owned since 2006</span><span>Your artwork, brought to life</span><span>Local pickup in Happy Valley <MapPin size={16}/></span></div></div>
 <section className="section wrap" id="create"><div className="section-heading" data-reveal><div><p className="eyebrow">Made for your everyday</p><h2>Find your starting point.</h2></div><p>Something thoughtful. Something useful.<br/>Something unmistakably you.</p></div><div className="category-grid">{[{name:'Custom apparel',description:'Your words. Your design. Your favorite new shirt.',icon:Shirt,id:'apparel',label:'WEAR YOUR IDEA'},{name:'Embroidery',description:'A lasting impression, one stitch at a time.',icon:Scissors,id:'embroidery',label:'MAKE YOUR MARK'},{name:'Engraved gifts',description:'Small details. A whole lot of meaning.',icon:PencilRuler,id:'engraving',label:'KEEP IT FOREVER'},{name:'Mugs & drinkware',description:'A personal touch for their daily ritual.',icon:Coffee,id:'drinkware',label:'MAKE EVERY DAY'}].map(({name,description,icon:Icon,id},index)=><a href={'/customize?category='+id} className={'category-card '+id} key={id} data-reveal data-delay={index*65}><div className="category-art"><Icon size={48} strokeWidth={1.2}/></div><div className="category-title"><h3>{name}</h3><ArrowUpRight size={22}/></div><p>{description}</p></a>)}</div></section>
 <section className="process section wrap" id="how"><p className="eyebrow">From idea to something real</p><h2>A personal touch.<br/>A simple process.</h2><div className="steps">{[['01','Choose your canvas','Pick apparel, drinkware, embroidery or an engraved gift.'],['02','Add your personal touch','Share your text, upload your artwork and tell us what you have in mind.'],['03','We’ll take it from here','We confirm the details, price and timing before anything is made.']].map(([n,t,d])=><div key={n} data-reveal><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
 <HomeDetails/><section id="visit" className="visit"><div className="wrap visit-inner"><div><p className="eyebrow">Your local creative studio</p><h2>Your neighborhood<br/>“can you make this?” shop.</h2><p>Find us at Clackamas Town Center in Happy Valley.<br/>Bring your idea. We’ll help with the rest.</p></div><div><p>12000 SE 82nd Ave, Suite 2024<br/>Happy Valley, OR 97086</p><a href="tel:5033038073">503-303-8073 <ArrowUpRight size={18}/></a><a href="mailto:sales@makeitpersonalized.com">sales@makeitpersonalized.com <ArrowUpRight size={18}/></a></div></div></section>
 </main><footer className="wrap footer"><a href="/" className="wordmark">make it<span>personalized.</span></a><p>A little more you. Since 2006.</p><a href="/requests">My requests</a><a href="/privacy">Privacy</a><span>© {new Date().getFullYear()} Make it Personalized</span></footer>
 </>;
}