import HomeDetails from '@/components/home-details';
import { ArrowUpRight, ArrowRight, Sparkles, MapPin, Shirt, Scissors, PencilRuler, Coffee } from 'lucide-react';
export default function Home() {
 return <>
 <div className="announcement">A little personal goes a long way. <span>Made in Happy Valley, Oregon.</span></div>
 <header className="site-header wrap"><a href="/" className="wordmark">make it<span>personalized<span className="brand-dot">.</span></span></a><nav aria-label="Main navigation"><a href="#create">What we make</a><a href="#how">How it works</a><a href="#visit">Visit the studio</a></nav><a className="button small" href="/customize">Start your project <ArrowUpRight size={17}/></a></header>
 <main>
 <section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span className="mini-star">✳</span> YOUR IDEA. OUR CRAFT.</p><h1>Ordinary things.<br/><span>Extraordinary</span><br/>personal touches.</h1><p className="hero-description">The shirt that says it all. The gift that gets kept. Custom printing, embroidery & engraving, made just for you.</p><div className="hero-actions"><a className="button" href="/customize">Make it yours <ArrowUpRight size={19}/></a><a className="text-link" href="#create">Explore what we make <ArrowRight size={17}/></a></div><p className="hero-note"><span className="status-dot"/> One item or a whole team. Let’s make it happen.</p></div><div className="hero-image"><img src="/products-hero.png" alt="Personalization concepts: a cotton shirt, embroidered cap, mug, tumbler and wood tag"/><div className="image-label"><Sparkles size={18}/><span>Made for your<br/><strong>kind of original.</strong></span></div><span className="image-caption">PRODUCT CONCEPTS · ENDLESS POSSIBILITIES</span></div></section>
 <div className="benefit-strip"><div className="wrap"><span>One item? Absolutely.</span><span>Family-owned since 2006</span><span>Your artwork, brought to life</span><span>Local pickup in Happy Valley <MapPin size={16}/></span></div></div>
 <section className="section wrap" id="create"><div className="section-heading"><div><p className="eyebrow">A BLANK CANVAS FOR YOUR NEXT IDEA</p><h2>What will you make?</h2></div><p>Something thoughtful. Something useful.<br/>Something unmistakably you.</p></div><div className="category-grid">{[{name:'Custom apparel',description:'Your words. Your design. Your favorite new shirt.',icon:Shirt,id:'apparel',label:'WEAR YOUR IDEA'},{name:'Embroidery',description:'A lasting impression, one stitch at a time.',icon:Scissors,id:'embroidery',label:'MAKE YOUR MARK'},{name:'Engraved gifts',description:'Small details. A whole lot of meaning.',icon:PencilRuler,id:'engraving',label:'KEEP IT FOREVER'},{name:'Mugs & drinkware',description:'A personal touch for their daily ritual.',icon:Coffee,id:'drinkware',label:'MAKE EVERY DAY'}].map(({name,description,icon:Icon,id,label})=><a href={'/customize?category='+id} className={'category-card '+id} key={id}><div className="category-art"><Icon size={48} strokeWidth={1.2}/><span>{label}</span></div><div className="category-title"><h3>{name}</h3><ArrowUpRight size={22}/></div><p>{description}</p></a>)}</div></section>
 <section className="process section wrap" id="how"><p className="eyebrow">FROM “WHAT IF” TO “THAT’S PERFECT”</p><h2>A simple idea.<br/>An easy way to make it real.</h2><div className="steps">{[['01','Choose your canvas','Pick apparel, drinkware, embroidery or an engraved gift.'],['02','Add your personal touch','Share your text, upload your artwork and tell us what you have in mind.'],['03','We’ll take it from here','We confirm the details, price and timing before anything is made.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
 <HomeDetails/><section id="visit" className="visit"><div className="wrap visit-inner"><div><p className="eyebrow">REAL PEOPLE. PERSONAL SERVICE.</p><h2>Your neighborhood<br/>“can you make this?” shop.</h2><p>Find us at Clackamas Town Center in Happy Valley.<br/>Bring your idea. We’ll help with the rest.</p></div><div><p>12000 SE 82nd Ave, Suite 2024<br/>Happy Valley, OR 97086</p><a href="tel:5033038073">503-303-8073 <ArrowUpRight size={18}/></a><a href="mailto:sales@makeitpersonalized.com">sales@makeitpersonalized.com <ArrowUpRight size={18}/></a></div></div></section>
 </main><footer className="wrap footer"><a href="/" className="wordmark">make it<span>personalized.</span></a><p>A little more you. Since 2006.</p><a href="/requests">My requests</a><a href="/privacy">Privacy</a><span>© {new Date().getFullYear()} Make it Personalized</span></footer>
 </>;
}