'use client';
import {useMemo,useState} from 'react';
import {Search,ArrowUpRight} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {type ShopProduct,priceLabel,productUrl} from '@/lib/shop';
export default function ProductCatalog({products}:{products:ShopProduct[]}){
const[query,setQuery]=useState('');const[sort,setSort]=useState('featured');
const shown=useMemo(()=>{const filtered=products.filter(p=>(p.name+' '+p.description).toLowerCase().includes(query.trim().toLowerCase()));return filtered.sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='name'?a.name.localeCompare(b.name):0)},[products,query,sort]);
return <><div className="catalog-controls"><label className="catalog-search"><Search size={19}/><span className="sr-only">Search products</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a tee, mug, gift…"/></label><Select value={sort} onValueChange={v=>v&&setSort(v)}><SelectTrigger className="catalog-sort" aria-label="Sort products"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="featured">Featured order</SelectItem><SelectItem value="low">Price: low to high</SelectItem><SelectItem value="high">Price: high to low</SelectItem><SelectItem value="name">Name: A to Z</SelectItem></SelectContent></Select></div><div className="catalog-meta"><p aria-live="polite">{shown.length} {shown.length===1?'item':'items'}</p><p>Catalog prices shown. Your final quote is confirmed before production.</p></div><div className="product-grid">{shown.map(p=><a href={productUrl(p)} key={p.id} className="product-card"><div className="product-photo">{p.image&&<img src={p.image} alt={p.name} width="600" height="600" loading="lazy" decoding="async"/>}</div><div className="product-card-copy"><span className="product-service">{p.service==='apparel'?'Custom apparel':p.service==='engraving'?'Engravable gift':p.service==='drinkware'?'Personalized drinkware':'Embroidery collection'}</span><h2>{p.name}</h2><div className="product-price"><span>{priceLabel(p.price)}</span><ArrowUpRight size={19}/></div></div></a>)}</div>{!shown.length&&<div className="catalog-empty"><h2>No items match “{query}”.</h2><p>Try a different word, or tell us about the item you have in mind.</p><button className="button secondary" onClick={()=>setQuery('')}>Clear search</button><a className="text-link" href="/customize">Request something custom</a></div>}</>}
