'use client';
import {useEffect,useRef,useState,useId,type SubmitEvent} from 'react';
import {ArrowLeft,ArrowRight,Check,Upload,FileImage,X,Shirt,Scissors,Coffee,PenTool,Minus,Plus,Sparkles} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {categories,colors,sizes,type Draft} from '@/lib/catalog';
import {shopProducts} from '@/lib/shop';
import {draftForCategory,quickItems,ideaError,artworkError,designHelpText} from '@/lib/order-flow';
type MC={registerTool:(tool:{name:string;description:string;inputSchema:object;execute:(input:unknown)=>unknown;annotations?:object},options:{signal:AbortSignal})=>unknown};
const icons={apparel:Shirt,embroidery:Scissors,engraving:PenTool,drinkware:Coffee};
const labels:Record<string,string>={apparel:'Clothing',embroidery:'Embroidery',engraving:'Engraved gifts',drinkware:'Mugs & bottles'};
function Picker({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(v:string)=>void}) {
 const id=useId();
 return <div className="field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger id={id} className="form-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>;
}
export default function Customize({initialDraft}:{initialDraft:Draft}){
 const[draft,setDraft]=useState(initialDraft),[step,setStep]=useState(0);
 const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState('');
 const[showChooser,setShowChooser]=useState(!shopProducts.some(p=>p.name===initialDraft.product&&p.service===initialDraft.category));
 const[detailsOpen,setDetailsOpen]=useState(false),[dragActive,setDragActive]=useState(false);
 const[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uploadError,setUploadError]=useState(''),[receipt,setReceipt]=useState('');
 const[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[website,setWebsite]=useState('');
 const titleRef=useRef<HTMLHeadingElement>(null),errorRef=useRef<HTMLParagraphElement>(null),fileInput=useRef<HTMLInputElement>(null);
 const draftRef=useRef(draft),keyRef=useRef(''),busyRef=useRef(false);
 const product=shopProducts.find(p=>p.name===draft.product&&p.service===draft.category);
 const Icon=icons[draft.category as keyof typeof icons]||Shirt;
 const update=(patch:Partial<Draft>)=>{const next={...draftRef.current,...patch};draftRef.current=next;setDraft(next);setError('')};
 const chooseCategory=(id:string)=>{update(draftForCategory(id,draftRef.current))};
 const go=(next:number)=>{if(busyRef.current)return;setStep(next);setError('');requestAnimationFrame(()=>titleRef.current?.focus())};
 const showError=(message:string)=>{setError(message);requestAnimationFrame(()=>errorRef.current?.focus())};
 useEffect(()=>{keyRef.current=crypto.randomUUID()},[]);
 useEffect(()=>{if(!file||!file.type.startsWith('image/')){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:MC}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=async()=>{try{
   await context.registerTool({name:'stage_custom_order_request',description:'Choose a service and stage text and quantity in the visible order form. Does not submit an order or contact details.',inputSchema:{type:'object',properties:{category:{type:'string',enum:categories.map(c=>c.id)},quantity:{type:'integer',minimum:1,maximum:5000},text:{type:'string',maxLength:500}},required:['category','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(busyRef.current)throw new Error('Please wait until this request finishes sending.');const v=input as {category?:string;quantity?:number;text?:string};const c=categories.find(c=>c.id===v?.category);if(!c||!Number.isInteger(v.quantity)||v.quantity!<1||v.quantity!>5000||typeof(v.text??'')!=='string'||(v.text??'').length>500)throw new Error('Choose a valid category, quantity from 1 to 5000, and text up to 500 characters.');const staged={...draftForCategory(c.id,draftRef.current),quantity:v.quantity!,text:v.text??''};draftRef.current=staged;setDraft(staged);setStep(0);setDetailsOpen(Boolean(v.text));setShowChooser(true);setError('');return {staged:true,category:c.id,quantity:v.quantity,submitted:false}}},{signal:lifecycle.signal});
   await context.registerTool({name:'read_custom_order_draft',description:'Read the selected product, quantity and personalization text from the current form. Does not include contact information.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){const d=draftRef.current;return {category:d.category,product:d.product,quantity:d.quantity,text:d.text}}},{signal:lifecycle.signal});
  }catch{/* The form also works in browsers without WebMCP. */}};
  void register();return()=>lifecycle.abort();
 },[]);
 const selectFile=(f:File|undefined)=>{if(!f)return;const message=artworkError(f);setUploadError(message);if(message){if(fileInput.current)fileInput.current.value='';return}setFile(f);setError('')};
 const removeFile=()=>{setFile(null);setUploadError('');if(fileInput.current)fileInput.current.value=''};
 const next=()=>{const message=ideaError(draft,Boolean(file));if(message){showError(message);return}go(1)};
 async function submit(e:SubmitEvent<HTMLFormElement>){
  e.preventDefault();if(busy)return;
  const message=ideaError(draft,Boolean(file));if(message){go(0);showError(message);return}
  if(!consent){showError('Please check the permission box so we can follow up about your idea.');return}
  busyRef.current=true;setBusy(true);setError('');
  try{
   const data=new FormData();data.set('draft',JSON.stringify(draft));data.set('name',name);data.set('email',email);data.set('phone',phone);data.set('consent','yes');data.set('website',website);
   if(!keyRef.current)keyRef.current=crypto.randomUUID();data.set('idempotencyKey',keyRef.current);
   if(file)data.set('artwork',file);
   const res=await fetch('/api/requests',{method:'POST',body:data});const result=await res.json() as {error?:string;reference:string};
   if(!res.ok)throw new Error(result.error||'Your request hasn’t been sent yet. Please try again.');
   setReceipt(result.reference);requestAnimationFrame(()=>titleRef.current?.focus());
  }catch(err){showError(err instanceof Error?err.message:'Your request hasn’t been sent yet. Please try again.')}finally{busyRef.current=false;setBusy(false)}
 }
 const preferences=[draft.color!=='Other / not sure'?draft.color:'',!['Please confirm size','Not applicable'].includes(draft.size)?draft.size:'',draft.placement!=='Tell us in notes'?draft.placement:'',draft.neededBy?'Preferred pickup: '+draft.neededBy:'',draft.purpose!=='Personal / gift'?draft.purpose:''].filter(Boolean);
 const itemPreview=<div className="chosen-item">{product?<img src={product.image} alt={product.name} width="72" height="72"/>:<span className="chosen-icon"><Icon size={27}/></span>}<div><span>{step===1?draft.quantity+' × '+labels[draft.category]:'Your starting point'}</span><strong>{draft.product}</strong></div><button type="button" className="text-link" onClick={()=>{if(step===1)go(0);else setShowChooser(!showChooser)}}>{step===1?'Edit':showChooser?'Done':'Change'}</button></div>;
 return <><header className="site-header wrap"><a className="wordmark" href="/">make it<span>personalized.</span></a><a className="text-link" href="/shop"><ArrowLeft size={16}/> Back to shop</a></header><main className="easy-order wrap">
 {receipt?<section className="success-panel friendly-success"><span className="success-icon"><Check size={32}/></span><p className="eyebrow">Over to us</p><h1 ref={titleRef} tabIndex={-1}>Thanks, {name.trim().split(' ')[0]}.<br/>We’ve got your idea.</h1><p>We’ll review your request and contact you at <strong>{email}</strong> to work out the details.</p><div className="receipt-details"><p><strong>{draft.quantity} × {draft.product}</strong></p><p>Request reference: <strong>{receipt}</strong></p><p>We’ll confirm your quote, artwork and pickup timing before production.</p></div><a href="/requests" className="button">View my request <ArrowRight size={18}/></a><p className="success-reassurance">No payment has been taken.</p><a href="/shop" className="text-link">Back to the shop</a></section>:<>
 <div className="easy-heading"><p className="eyebrow">A little idea is all it takes</p><h1>Let’s make something yours.</h1><p>Tell us what you’re thinking. We’ll help with the details.</p><span className="quote-reassurance"><Check size={15}/> A personal quote. No payment today.</span></div>
 <ol className="easy-progress" aria-label="Request progress">{['Your idea','Your details'].map((label,i)=><li key={label} aria-current={i===step?'step':undefined} className={step===i?'current':step>i?'complete':''}>{i<step?<button type="button" disabled={busy} onClick={()=>go(i)}><span><Check size={14}/></span>{label}</button>:<><span>{i+1}</span>{label}</>}</li>)}</ol>
 <section className="easy-card" key={step}><h2 ref={titleRef} tabIndex={-1}>{step===0?'What would you like to make?':'Where can we reach you?'}</h2><p className="easy-subtitle">{step===0?'Start with an item and a little inspiration.':'Just a name and email, so we can send your quote.'}</p>
 {step===0?<div>
 {(!showChooser||product)&&itemPreview}
 {showChooser&&<div className="item-chooser"><RadioGroup value={draft.category} onValueChange={v=>chooseCategory(String(v))} className="quick-categories" aria-label="What would you like to personalize?">{categories.map(c=>{const CategoryIcon=icons[c.id];return <label key={c.id} htmlFor={'service-'+c.id} className={'quick-category '+(draft.category===c.id?'selected':'')}><RadioGroupItem id={'service-'+c.id} value={c.id}/><CategoryIcon size={24}/><span>{labels[c.id]}</span></label>})}</RadioGroup><Picker label="Choose a starting point" value={draft.product} options={quickItems(draft)} onChange={product=>update({product})}/><a href="/shop" className="browse-products">Looking for a specific product? Browse the shop →</a></div>}
 <div className="quantity-row"><div><label htmlFor="quantity">How many?</label><p>One is absolutely fine.</p></div><div className="quantity-control"><button type="button" aria-label="One fewer item" disabled={draft.quantity<=1} onClick={()=>update({quantity:Math.max(1,(draft.quantity||1)-1)})}><Minus size={17}/></button><input id="quantity" aria-label="Number of items" type="number" inputMode="numeric" min="1" max="5000" value={draft.quantity||''} onChange={e=>update({quantity:Number(e.target.value)})}/><button type="button" aria-label="One more item" disabled={draft.quantity>=5000} onClick={()=>update({quantity:Math.min(5000,(draft.quantity||0)+1)})}><Plus size={17}/></button></div></div>
 <div className="field idea-field"><label htmlFor="idea">Tell us your idea</label><textarea id="idea" rows={4} maxLength={2000} value={draft.notes} onChange={e=>update({notes:e.target.value})} placeholder="For example: a birthday shirt for Maya, with her name in purple." aria-describedby="idea-hint"/><p id="idea-hint" className="field-hint">A few words are enough. You can also just attach your artwork below.</p>{!draft.notes&&<button type="button" className="design-help" onClick={()=>update({notes:designHelpText})}><Sparkles size={15}/> I’d like design help</button>}</div>
 <div className={'easy-upload '+(dragActive?'drag-active':'')} onDragOver={e=>{e.preventDefault();setDragActive(true)}} onDragLeave={()=>setDragActive(false)} onDrop={e=>{e.preventDefault();setDragActive(false);selectFile(e.dataTransfer.files[0])}}><Upload size={23}/><div><label htmlFor="artwork">{file?'Replace artwork':'Add artwork or a photo'} <span>(optional)</span></label><p>Choose a file or drop it here · PNG, JPG or PDF · Up to 5 MB</p><input className="upload-input" ref={fileInput} id="artwork" type="file" accept="image/png,image/jpeg,application/pdf" onChange={e=>selectFile(e.target.files?.[0])}/></div></div>
 {uploadError&&<p className="upload-error" role="alert">{uploadError}{file?' Your previous file is still attached.':''}</p>}
 {file&&<div className="attached-artwork">{preview?<img src={preview} alt="Your artwork preview"/>:<FileImage size={25}/>}<div><strong>{file.name}</strong><span>Attached to your request</span></div><button type="button" onClick={removeFile} aria-label="Remove artwork"><X size={19}/></button></div>}
 <Accordion className="optional-details" value={detailsOpen?['details']:[]} onValueChange={value=>setDetailsOpen(value.includes('details'))}><AccordionItem value="details"><AccordionTrigger><span>Have specific details? <small>Optional</small></span></AccordionTrigger><AccordionContent><p className="optional-intro">Only fill in what you know. We’ll work out anything else together.</p><div className="field"><label htmlFor="print-text">Exact text to print or engrave</label><textarea rows={2} id="print-text" value={draft.text} maxLength={500} placeholder="A name, date or message" onChange={e=>update({text:e.target.value})}/></div><div className="form-grid"><Picker label="Color preference" value={draft.color} options={colors} onChange={color=>update({color})}/>{['apparel','embroidery'].includes(draft.category)&&<Picker label="Size preference" value={draft.size} options={sizes} onChange={size=>update({size})}/>}<Picker label="Where should the design go?" value={draft.placement} options={['Tell us in notes','Front','Back','Front & back']} onChange={placement=>update({placement})}/><div className="field"><label htmlFor="date">Preferred pickup date</label><input id="date" type="date" min={new Date().toLocaleDateString('en-CA')} value={draft.neededBy} onChange={e=>update({neededBy:e.target.value})}/></div><Picker label="Who is it for?" value={draft.purpose} options={['Personal / gift','Business / team','Event / celebration']} onChange={purpose=>update({purpose})}/></div><p className="field-hint">For mixed sizes, special colors or a particular placement, add a note to your idea above. We’ll confirm your preferred date.</p></AccordionContent></AccordionItem></Accordion>
 {error&&<p className="form-error" role="alert" tabIndex={-1} ref={errorRef}>{error}</p>}<div className="easy-actions"><span>Next: your contact details</span><button type="button" className="button" onClick={next}>Continue <ArrowRight size={18}/></button></div>
 </div>:<form onSubmit={submit}><fieldset disabled={busy} className="contact-fields"><div className="request-recap">{itemPreview}<div className="recap-idea">{draft.notes&&<p className="preserve">{draft.notes}</p>}{draft.text&&<p className="preserve"><strong>Exact text:</strong> {draft.text}</p>}{file&&<p className="recap-file"><FileImage size={16}/> {file.name}</p>}{preferences.length>0&&<p className="recap-preferences">{preferences.join(' · ')}</p>}</div></div><div className="form-grid"><div className="field"><label htmlFor="name">Your name</label><input id="name" required minLength={2} maxLength={100} autoComplete="name" value={name} placeholder="Your name" onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor="email">Email address</label><input id="email" required type="email" maxLength={254} autoComplete="email" value={email} placeholder="you@example.com" onChange={e=>setEmail(e.target.value)}/></div></div><div className="field phone-field"><label htmlFor="phone">Phone number <span>(optional)</span></label><input id="phone" type="tel" autoComplete="tel" maxLength={30} value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></div><label className="consent" htmlFor="request-consent"><Checkbox id="request-consent" checked={consent} onCheckedChange={v=>setConsent(Boolean(v))}/><span>You can contact me about this request. I have permission to use any artwork I’m sending. <a href="/privacy">Privacy</a></span></label>{error&&<p className="form-error" role="alert" tabIndex={-1} ref={errorRef}>{error}</p>}<div className="easy-actions"><button type="button" className="text-link" onClick={()=>go(0)}><ArrowLeft size={16}/> Back</button><button type="submit" className="button">{busy?'Sending your idea…':'Request my quote'} {!busy&&<ArrowRight size={18}/>}</button></div><p className="send-reassurance">We’ll confirm price, artwork and pickup timing before anything is made.</p></fieldset></form>}
 </section><p className="easy-help">Prefer to talk it through? <a href="tel:5033038073">Call 503-303-8073</a></p>
 </>}
 </main><footer className="wrap footer easy-footer"><a href="/privacy">Privacy</a><p>Made personal in Happy Valley, Oregon.</p><a href="/requests">My requests</a></footer></>;
}
