'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,Upload,FileImage,ShieldCheck,MapPin,Sparkles,X} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {categories,defaultDraft,sizes,colors,type Draft} from '@/lib/catalog';
type MC={registerTool:(tool:{name:string;description:string;inputSchema:object;execute:(input:unknown)=>unknown;annotations?:object},options:{signal:AbortSignal})=>unknown};
function Picker({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(v:string)=>void}) { return <div className="field"><label>{label}</label><Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label} className="form-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div> }
export default function Customize(){
 const[draft,setDraft]=useState<Draft>(defaultDraft);const[step,setStep]=useState(0);const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState('');const[consent,setConsent]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[receipt,setReceipt]=useState('');const[name,setName]=useState('');const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[website,setWebsite]=useState('');const titleRef=useRef<HTMLHeadingElement>(null);const draftRef=useRef(draft); draftRef.current=draft;const keyRef=useRef('');
 const category=categories.find(c=>c.id===draft.category)||categories[0];
 const update=(patch:Partial<Draft>)=>{setDraft(d=>({...d,...patch}));setError('')};
 const chooseCategory=(id:string)=>{const c=categories.find(c=>c.id===id);if(!c)return;update({category:c.id,product:c.products[0],size:c.id==='apparel'?'M':'Not applicable',color:c.id==='apparel'?'White':'Natural / original',placement:c.id==='apparel'?'Front':'Tell us in notes'})};
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('category');if(id){const c=categories.find(c=>c.id===id);if(c)setDraft(d=>({...d,category:c.id,product:c.products[0],size:c.id==='apparel'?'M':'Not applicable',color:c.id==='apparel'?'White':'Natural / original',placement:c.id==='apparel'?'Front':'Tell us in notes'}));}if(new URLSearchParams(window.location.search).get('purpose')==='business')setDraft(d=>({...d,purpose:'Business / team'})); keyRef.current=crypto.randomUUID();},[]);
 useEffect(()=>{if(!file||!file.type.startsWith('image/')){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 useEffect(()=>{const context=(document as Document&{modelContext?:MC}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=async()=>{try{await context.registerTool({name:'stage_custom_order_request',description:'Choose a service and stage text and quantity in the visible order form. Does not submit an order or contact details.',inputSchema:{type:'object',properties:{category:{type:'string',enum:categories.map(c=>c.id)},quantity:{type:'integer',minimum:1,maximum:5000},text:{type:'string',maxLength:500}},required:['category','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const v=input as {category?:string;quantity?:number;text?:string};const c=categories.find(c=>c.id===v?.category);if(!c||!Number.isInteger(v.quantity)||v.quantity!<1||v.quantity!>5000||typeof(v.text??'')!=='string'||(v.text??'').length>500)throw new Error('Choose a valid category, quantity from 1 to 5000, and text up to 500 characters.');const staged={...draftRef.current,category:c.id,product:c.products[0],quantity:v.quantity!,text:v.text??'',size:c.id==='apparel'?'M':'Not applicable',color:c.id==='apparel'?'White':'Natural / original',placement:c.id==='apparel'?'Front':'Tell us in notes'};draftRef.current=staged;setDraft(staged);setStep(1);setError('');return {staged:true,category:c.id,quantity:v.quantity,submitted:false}}},{signal:lifecycle.signal});await context.registerTool({name:'read_custom_order_draft',description:'Read the selected product, quantity and personalization text from the current form. Does not include contact information.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){const d=draftRef.current;return {category:d.category,product:d.product,quantity:d.quantity,text:d.text}}},{signal:lifecycle.signal})}catch{ /* Ordinary browsers do not need WebMCP. */ }};void register();return()=>lifecycle.abort()},[]);
 const go=(n:number)=>{setStep(n);setError('');requestAnimationFrame(()=>titleRef.current?.focus())};
 const next=()=>{if(!Number.isInteger(draft.quantity)||draft.quantity<1||draft.quantity>5000){setError('Please enter a quantity from 1 to 5,000.');return;}if(step===1&&!draft.text.trim()&&!draft.notes.trim()&&!file){setError('Add your text, an artwork file, or a few notes about your idea.');return;}go(step+1)};
 const selectFile=(f:File|undefined)=>{setError('');if(!f){setFile(null);return;}if(!['image/png','image/jpeg','application/pdf'].includes(f.type)||f.size>5*1024*1024){setError('Choose a PNG, JPG or PDF up to 5 MB.');return;}setFile(f)};
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;if(!consent){setError('Please agree to be contacted about your request.');return;}setBusy(true);setError('');try{const data=new FormData();data.set('draft',JSON.stringify(draft));data.set('name',name);data.set('email',email);data.set('phone',phone);data.set('consent','yes');data.set('website',website);data.set('idempotencyKey',keyRef.current);if(file)data.set('artwork',file);const res=await fetch('/api/requests',{method:'POST',body:data});const result=await res.json() as {error?:string;reference:string};if(!res.ok)throw new Error(result.error||'We could not save your request. Please try again.');setReceipt(result.reference);}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Please try again.')}finally{setBusy(false)}}
 return <><header className="site-header wrap"><a className="wordmark" href="/">make it<span>personalized.</span></a><a className="text-link" href="/"><ArrowLeft size={16}/> Back to the studio</a></header><main className="builder wrap">
 {receipt?<section className="success-panel"><span className="success-icon"><Check size={34}/></span><p className="eyebrow">YOUR IDEA IS IN GOOD HANDS</p><h1>Request received.</h1><p>Your reference is <strong>{receipt}</strong>. Keep it handy when contacting the studio.</p><div className="receipt-details"><p><strong>{draft.quantity} × {draft.product}</strong><br/>{category.name} · Local pickup</p><p>We’ll review your idea and confirm the price, artwork and timing before production. No payment has been taken.</p><p>Contact details: {email}</p></div><a href="/requests" className="button">View my requests <ArrowRight size={18}/></a><a href="/" className="text-link">Back to the studio</a></section>:<>
 <div className="builder-heading"><p className="eyebrow">LET’S MAKE SOMETHING PERSONAL</p><h1>Your idea starts here.</h1><p>Tell us what you have in mind. We’ll help bring it to life.</p></div>
 <ol className="step-indicator" aria-label="Order request progress">{['Your canvas','Your personal touch','Review & send'].map((s,i)=><li key={s} aria-current={step===i?'step':undefined} className={step===i?'active':step>i?'done':''}><span>{step>i?<Check size={16}/>:i+1}</span>{s}</li>)}</ol>
 <div className="builder-layout"><section className="builder-main"><h2 ref={titleRef} tabIndex={-1}>{['First, choose your canvas.','Make it unmistakably yours.','One last look. Then it’s over to us.'][step]}</h2>
 {step===0&&<><p className="muted">A single gift, a team order, or something entirely your own.</p><RadioGroup value={draft.category} onValueChange={v=>chooseCategory(String(v))} className="service-options" aria-label="Service">{categories.map(c=><label key={c.id} className={'service-option '+(draft.category===c.id?'selected':'')}><RadioGroupItem value={c.id}/><span><strong>{c.name}</strong><small>{c.description}</small></span></label>)}</RadioGroup><div className="form-grid"><Picker label="Choose an item" value={draft.product} options={category.products} onChange={product=>update({product})}/><div className="field"><label htmlFor="quantity">How many?</label><input id="quantity" type="number" min="1" max="5000" value={draft.quantity||''} onChange={e=>update({quantity:Number(e.target.value)})}/></div><Picker label="This project is for" value={draft.purpose} options={['Personal / gift','Business / team','Event / celebration']} onChange={purpose=>update({purpose})}/></div><p className="field-hint">Bringing your own item? Choose “My own” above. We’ll confirm its suitability before starting.</p></>}
 {step===1&&<><div className="form-grid"><Picker label="Color preference" value={draft.color} options={colors} onChange={color=>update({color})}/>{['apparel','embroidery'].includes(draft.category)&&<Picker label="Size" value={draft.size} options={sizes} onChange={size=>update({size})}/>}<Picker label="Personalization placement" value={draft.placement} options={['Front','Back','Front & back','Tell us in notes']} onChange={placement=>update({placement})}/><div className="field"><label htmlFor="date">Preferred pickup date <span>(optional)</span></label><input id="date" type="date" min={new Date().toLocaleDateString('en-CA')} value={draft.neededBy} onChange={e=>update({neededBy:e.target.value})}/></div></div><div className="field"><label htmlFor="personal-text">What should it say? <span>(optional)</span></label><textarea id="personal-text" rows={3} maxLength={500} placeholder="A name, a meaningful date, your favorite line…" value={draft.text} onChange={e=>update({text:e.target.value})}/><span className="field-hint">Use the exact spelling and capitalization you would like.</span></div>
 <div className="upload-box"><Upload size={23}/><div><label htmlFor="artwork"><strong>Add your artwork</strong></label><p>PNG, JPG or PDF · Up to 5 MB · Optional</p><input id="artwork" type="file" accept="image/png,image/jpeg,application/pdf" onChange={e=>selectFile(e.target.files?.[0])}/></div></div>{file&&<div className="file-chip"><FileImage size={16}/><span>{file.name}</span><button type="button" aria-label="Remove artwork" onClick={()=>setFile(null)}><X size={17}/></button></div>}{preview&&<img className="artwork-preview" src={preview} alt="Your uploaded artwork"/>}
 <div className="field"><label htmlFor="notes">Anything else we should know?</label><textarea id="notes" rows={3} maxLength={2000} placeholder="Design placement, mixed sizes, item details, or a little help with your idea…" value={draft.notes} onChange={e=>update({notes:e.target.value})}/></div><p className="field-hint">Your date is a preference, not a confirmed deadline. Ask the studio about urgent requests.</p></>}
 {step===2&&<form id="request-form" onSubmit={submit}><div className="review-line"><div><strong>{draft.quantity} × {draft.product}</strong><p>{draft.color} · {draft.size} · {draft.placement}</p></div><button type="button" className="text-link" onClick={()=>go(0)}>Edit</button></div><div className="review-line"><div><strong>Your personalization</strong><p className="preserve">{draft.text||'No text requested'}</p>{file&&<p>Artwork: {file.name}</p>}{draft.notes&&<p className="preserve">{draft.notes}</p>}</div><button type="button" className="text-link" onClick={()=>go(1)}>Edit</button></div><h3 className="contact-heading">Where can we reach you?</h3><div className="form-grid"><div className="field"><label htmlFor="name">Your name</label><input required autoComplete="name" id="name" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor="email">Email address</label><input required autoComplete="email" type="email" id="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label htmlFor="phone">Phone <span>(optional)</span></label><input autoComplete="tel" type="tel" id="phone" maxLength={30} value={phone} onChange={e=>setPhone(e.target.value)}/></div></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></div><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(Boolean(v))}/><span>I agree to be contacted about this request and have permission to use the submitted artwork. <a href="/privacy">Privacy information</a></span></label><p className="field-hint">This sends an order request. Price, availability and your proof are confirmed before production. No payment is collected here.</p></form>}
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions">{step>0?<button type="button" className="button secondary" onClick={()=>go(step-1)} disabled={busy}><ArrowLeft size={16}/> Back</button>:<span/>}{step<2?<button type="button" className="button" onClick={next}>Continue <ArrowRight size={18}/></button>:<button type="submit" form="request-form" className="button" disabled={busy}>{busy?'Saving your request…':'Send my request'} <ArrowUpRight size={18}/></button>}</div>
 </section><aside className="order-summary"><img src="/products-futuristic.png" alt="Custom apparel and personalized gift concepts"/><div className="summary-content"><p className="eyebrow">YOUR PROJECT, AT A GLANCE</p><h3>{draft.product}</h3><dl><div><dt>Service</dt><dd>{category.name}</dd></div><div><dt>Quantity</dt><dd>{draft.quantity||'—'}</dd></div><div><dt>For</dt><dd>{draft.purpose}</dd></div><div><dt>Pickup</dt><dd>Happy Valley, OR</dd></div></dl><div className="price-note"><ShieldCheck size={22}/><p><strong>Made to order. Quoted for you.</strong><br/>Final pricing confirmed after review.</p></div><p className="summary-help">Have a question?<br/><a href="tel:5033038073">Call 503-303-8073 <ArrowUpRight size={14}/></a></p></div></aside></div>
 </>}</main><footer className="wrap footer"><a href="/privacy">Privacy</a><p>Made personal in Happy Valley, Oregon.</p><a href="/requests">My requests</a></footer></>
}
